apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: monet-web-app-tls
  namespace: monet-app
spec:
  secretName: monet-web-app-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - ${APP_DOMAIN}
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  usages:
  - digital signature
  - key encipherment 