apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: mlflow-tls
  namespace: mlflow
spec:
  secretName: mlflow-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
  - ${MLFLOW_DOMAIN}
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
  usages:
  - digital signature
  - key encipherment 